### ISSUE TITLE
Domain extraction bug

### ISSUE THREAD

**Issue by ghostwords** [oncletom/tld.js#53]
Two similar failing examples:

```javascript
tldjs.getDomain("http://cdn.jsdelivr.net/g/jquery@1.8.2,jquery.waypoints@2.0.2,qtip2@2.2.1,typeahead.js@0.9.3,sisyphus@0.1,jquery.slick@1.3.15,fastclick@1.0.3")
//"0.3"
tldjs.getDomain("http://cdn.jsdelivr.net/g/jquery@1.8.2,jquery.waypoints@2.0.2,qtip2@2.2.1,typeahead.js@0.9.3,sisyphus@0.1,jquery.slick@1.3.15,fastclick@1.0.3,jquery.cookie@1.3.1,jquery.jscroll@2.2.4")
//"2.4"
```
Observed in the Web version (http://wzrd.in/standalone/tldjs) and in tld.js from npm.

Compare with [tldextract](https://github.com/john-kurkowski/tldextract) (Python module):
```shell
$ curl "http://tldextract.appspot.com/api/extract?url=http://cdn.jsdelivr.net/g/jquery@1.8.2,jquery.waypoints@2.0.2,qtip2@2.2.1,typeahead.js@0.9.3,sisyphus@0.1,jquery.slick@1.3.15,fastclick@1.0.3"
{"domain": "jsdelivr", "subdomain": "cdn", "suffix": "net", "tld": "net"}
```

**Comment by oncletom** [comment]
Interesting one! It should definitely have caught the `.net`.

Thanks for reporting it — will try to find some time to fix this.

**Comment by myndzi** [comment]
So, this library doesn't probably process URIs correctly; there are some problems with `url.parse()` on certain kinds of strings that are rooted in the actual RFC definition of URLs and how to process them. For example, in RFC 3986, a valid URI example given is `urn:example:animal:ferret:nose`, and this contains no hostname; only a scheme and a path are provided.

Since this library is specifically concerned with host and domain names, it is a safe assumption that any value passed in should contain the `authority` portion of the URI; this is distinguished from the previous example by the presence of `//` after the scheme.

It should therefore be relatively straightforward to do the following:

- Check whether the scheme or `//` is supplied
- If not, prepend `//`
- Use URL.parse to extract the hostname (useSlashes = true)

This process gives the correct results from the example URIs above and tests pass.

I'm submitting a patch shortly.
