### ISSUE TITLE
Use protobuf as a way to encode/decode tld list

### ISSUE THREAD

**Issue by oncletom** [oncletom/tld.js#56]

**Comment by myndzi** [comment]
The DAWG direction was a good one I think; I actually wrote some code a couple weeks ago to create and encode a DAWG as a binary buffer, but lookup became complicated because of a couple choices I made. I discovered during the work, though, that you can represent characters in domain names as the low 6 bits of each character, which makes encoding it pretty compact in some ways. In the end the file I got didn't seem to be much smaller than the existing json, though, despite some interesting optimizations I found.

You're probably better off just doing a trie, which makes it easier to store data. 

Other useful tidbits: the number of nodes with more than one edge is very low; the number of exceptions was 6 last I checked; it's quite sufficient to simply store strings and match against them, so there's no need to break hostnames up into chunks.

Protobuf could be a useful way to encode the DAWG data into a compact file or transport form, but that's not the part that matters as far as memory usage of the application itself; my goal was to create a binary form I could load into a single buffer and run lookups against. I tried to build it in such a way that addressing other nodes would be able to use as few bits as possible, but it turns out 16 bits was the number it chose, so at some point I should be able to simplify the lookup code perhaps.

The format I went with is something like this for each node:
<header byte>
<one or more chars>
<zero or more child nodes>

The header byte consists of one bit to say whether words arrived at on this node might be exception rules, and 7 bits for the number of child nodes; each char is the low 6 bits of the (lowercase) characters from the string; lowercase a-z does not overlap with 0-9, -, ., * in this way. The top two bits are used for the 'is final' flag (is this character the final character of a word in the DAWG) and the 'end of list' flag (the chain of chars is done, after this is children). The child addresses erquired 15 (16?) bits, so I used a length representation instead of a flag bit. 

Lookup is something like (start at root node, read dummy char, iterate over children) -> for each child, read its address, check its character against the position in the word being looked up; on success, check zero or more characters against zero or more characters in the string being tested; if the chars at the current node are exhausted, iterate over the children and repeat. When there's no match, fail; when the input string runs out, fail unless the isFinal bit is 1 for the character we wound up on. Strings are stored backwards (right to left)

I wind up with 51269 bytes. The lookup code isn't functional yet. If you're interested in pursuing this path I am happy to share code or may be able to work on it some more.

**Comment by oncletom** [comment]
Did you make some progress on this? I think of simply going over object structures as they will be easy to iterate in the browser, without having to rely on the existence/polyfilling TypeArray, at least for now.

What do you think?

**Comment by oncletom** [comment]
Favouring #57.
