### ISSUE TITLE
Find a faster way to iterate over the ruleset

### ISSUE THREAD

**Issue by oncletom** [oncletom/tld.js#57]
Parsing + RegEx is definitely too slow even though it is solid.

Available options:
- [ ] [ndarray](https://www.npmjs.com/package/ndarray)
- [ ] per row tld + binary flags

**Comment by olivierbeaulieu** [comment]
Hey @oncletom,

Is there a reason why the rules.json file only has one level nested? For example, most of the speed problems are due to numerous regexes being run. The largest ruleset is .jp - and is structured like so:
```
{
	"jp": "asaminami.hiroshima|daiwa.hiroshima|etajima.hiroshima|fuchu.hiroshima|fukuyama.hiroshima|hatsukaichi.hiroshima"
}
```

Wouldn't it much faster if we `.split('.')` the domains, and nested the ruleset as far as needed? For example:

```
{
	jp: {
		hiroshima: {
			asaminami: {},
			daiwa: {},
			etajima: {},
			fuchu: {},
			fukuyama: {},
			hatsukaichi: {}
		}
	}
}```

This would allow for infinite nesting (although I don't think anything would require more than 3 levels) and would require no regexes. It most definitely would be wayyyyy faster. That's the solution that's used in a similar C++ lib: https://github.com/kejinlu/KKDomain/blob/master/KKDomain/Resources/etld.plist

Let me know what you think, I can implement these changes pretty soon.

**Comment by oncletom** [comment]
Hi @olivierbeaulieu,

yeah I think at the beginning I was looking for a compact way of bundling the list for the browser.
But in the end RegExp are not speed efficient and simpler/bitwise operations should be preferred – browser compression will certainly do its job and reduce the filesize for us.

I guess iterating over Object structures would be 1/ faster to parse, 2/ faster to iterate and 3/ easier to maintain.

If you have time I would be happy to see your PR and merge it :-)

**Comment by remusao** [comment]
Hi @oncletom 

If this is still something we are interested in, I'm willing to contribute some patch to implement this more efficient data-structure. I actually did something very similar once in another project (to cache the results of tldjs actually, and I can confirm it was indeed way faster!). If you give me some pointers about where to look I can give it a try!

Thanks,

**Comment by remusao** [comment]
@oncletom Shall we close this issue now that #97 has been merged?

**Comment by oncletom** [comment]
@remusao totally, good reminder 🙂
