### ISSUE TITLE
Expose methods as functions (bound methods)

### ISSUE THREAD

**Issue by Treora** [oncletom/tld.js#86]
Currently, importing a single function from a module (in ES6) like so:
```
import { getDomain } from 'tldjs';
getDomain(url)
```
fails with:
```
TypeError: Cannot read property 'isValid' of undefined
    at getDomain (.....)
```
This happens because getDomain relies on `this` being the `tldjs` object.

To fix this, could you perhaps expose the methods as independent functions?

**Comment by oncletom** [comment]
@Treora yeah it would be totally doable but it would imply to possibly break the API. Which is not a bad thing considering it is more a functional library rather than a _class_, really.

I see a few changes to operate:
- `validHosts` is bound to the class instance, and is used by `#getDomain` and `#isValid`;
- `#getRulesForTld` is used by `#getDomain`; it relies on `this.rules` to operate;
- static methods can be taken out so that's an easy job.

Maybe the easiest move would be to:
1. make everything as an independent function (some with more parameters)
2. `tldjs` exports an object with partially applied `rules` (for convenience)

I suppose if people want to feed it different rules, they would have to do some more work but well, it can be documented or made easier for them if needed.

What do you think?

**Comment by Treora** [comment]
You could opt to keep the API exactly the same if desired: you could just pass each function through [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind), so that its `this` will always be the `tld` instance.

If you wish to clean things up though, I would stop having `rules` and `validHosts` as global state of the module. Partially applied rules is indeed one way to go, or you could let the user 'recreate the module' with custom rules, for example like so:
```
function factory(rules, validHosts) {
    function getDomain(url) {
       ...rules[...url...]...
    }
    ...
    return {
        getDomain: getDomain,
        getSubdomain: getSubdomain,
        ...
        withCustomRules: factory
    }
}
module.exports = factory(require('rules.json'), [])
```

I have no strong opinion either way.

**Comment by oncletom** [comment]
@Treora, feel free to have a look at #86 to see if it fits your need. I had to change the way valid hosts were assigned as I don't think it is possible to track a mutated bound array.

**Comment by Treora** [comment]
Awesome. I almost feel guilty about having triggered such a code reorganisation effort with my tiny complaint. Thanks for your noble labour!

**Comment by oncletom** [comment]
No problem, it was some kind of distraction for the mind :-)
